apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tienda-db-pvc
  namespace: tienda
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 5Gi # Pide un disco de 5 Gigabytes