name: CI/CD Tienda Perritos - Frontend

on:
  push:
    branches: [ "deploy" ]
    paths:
      - "frontend/**"

jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build y Push imagen Frontend a ECR
      run: |
        cd frontend
        docker build -t tienda-frontend .
        docker tag tienda-frontend:latest ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest
        docker push ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest

    - name: Descargar task definition actual
      run: |
        aws ecs describe-task-definition \
          --task-definition tienda-frontend-td \
          --query taskDefinition > task-definition-frontend.json

    - name: Actualizar imagen en task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition-frontend.json
        container-name: tienda-frontend
        image: ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest

    - name: Deploy a ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ secrets.ECS_SERVICE_FRONTEND }}
        cluster: ${{ secrets.ECS_CLUSTER }}
        wait-for-service-stability: true